### PR TITLE
chore: Update readme with new charm name

### PR DESCRIPTION
**Pull request by dashmage**

### CODE REVIEW

**Comment by dashmage** [comment]
One thing to note is that the new charm currently doesn't have a stable release and needs `--channel edge` to be deployed. But this will soon be rectified once we promote a build to stable in the new charm as well.

**Review by agileshaw — COMMENTED** [review]
There are some links in the README that are still pointing to Launchpad, maybe we should update them also?

**Review by rgildein — CHANGES_REQUESTED** [review]
Please update the whole README.md with proper links to GitHub.

**Comment by rgildein** [comment]
> One thing to note is that the new charm currently doesn't have a stable release and needs `--channel edge` to be deployed. But this will soon be rectified once we promote a build to stable in the new charm as well.

I think it's ok, because if we add `--channel edge`, it will be released to the stable with that flag.

**Comment by dashmage** [comment]
@agileshaw , @rgildein - I just checked the LP links again on the README and they  refer and point correctly to the [upstream snap](https://launchpad.net/juju-backup-all) which is on LP itself currently and not migrated to GitHub since we thought the charm is more in use and the effort to move the snap over wouldn't be worth it.

**Review by Pjack — APPROVED** [review]

**Review by agileshaw — APPROVED** [review]

**Review by rgildein — APPROVED** [review]

**Pull request merged**
